### ISSUE TITLE
Result of duplicated entries

### ISSUE THREAD

**Issue by biowander** [xgrau/possvm-orthology#19]
Hello! Your work is outstanding! When I run the following command python possvm.py -i myTree.txt -p myTree --skipprint -o myTree -printallpairs, the results contain a large number of duplicates, and the homology labels for the pairs are inconsistent. Could you help identify the problem?
![possvm](https://github.com/user-attachments/assets/16eb92df-6888-4ac8-b846-20ace1256dc2)
The following is my tree file:
((Ch_tr|A0A2K3E088|A0A2K3E088_CHLRE:1.6302,(Os_tr|A0A0P0XD77|A0A0P0XD77_ORYSJ:5e-09,Si_tr|A0A3Q7H4Z5|A0A3Q7H4Z5_SOLLC:0.513192):0.953278):0.0753276,(Ch_tr|A0A2K3D0Q4|A0A2K3D0Q4_CHLRE:2.00138,((((Si_tr|A0A3Q7HSI4|A0A3Q7HSI4_SOLLC:0.351172,(Os_tr|Q0JBB7|Q0JBB7_ORYSJ:0.109545,Zm_tr|A0A1D6E4A2|A0A1D6E4A2_MAIZE:0.155835):0.424373):0.239,(Zm_tr|K7U275|K7U275_MAIZE:0.487332,(Si_tr|A0A3Q7FJJ7|A0A3Q7FJJ7_SOLLC:0.324866,(At_sp|F4HYR6|SBT24_ARATH:0.357564,Si_tr|A0A3Q7G8Y3|A0A3Q7G8Y3_SOLLC:0.454888):0.0274685):0.163244):0.322451):0.0647452,(((Os_tr|Q5Z852|Q5Z852_ORYSJ:0.0373762,(Zm_tr|C0P6H8|C0P6H8_MAIZE:0.0350936,Zm_tr|A0A1D6GUX8|A0A1D6GUX8_MAIZE:0.022047):0.0436249):0.14386,(Si_tr|A0A3Q7I1E3|A0A3Q7I1E3_SOLLC:0.130674,(At_sp|O64481|SBT25_ARATH:0.0796636,At_sp|Q9SZV5|SBT26_ARATH:0.0567206):0.0607848):0.164411):0.351765,((((Os_tr|Q94EF5|Q94EF5_ORYSJ:0.067774,(Zm_tr|A0A1D6NAI7|A0A1D6NAI7_MAIZE:0.0355317,Zm_tr|A0A1D6GAL4|A0A1D6GAL4_MAIZE:0.03408):0.0553295):0.219624,(Si_tr|A0A3Q7FH34|A0A3Q7FH34_SOLLC:0.178832,(Si_tr|A0A3Q7EY82|A0A3Q7EY82_SOLLC:0.195135,Si_tr|A0A3Q7FMZ3|A0A3Q7FMZ3_SOLLC:0.0687197):0.0203524):0.0663939):0.0348784,(At_sp|Q9SUN6|SBT22_ARATH:0.134707,((At_sp|Q9FI12|SBT23_ARATH:0,At_tr|A0A1P8BHH8|A0A1P8BHH8_ARATH:0):5e-09,At_tr|A0A1P8BHI3|A0A1P8BHI3_ARATH:0.0145056):0.153165):0.138699):0.0376386,At_sp|Q9SA75|SBT21_ARATH:0.284264):0.503259):0.0813316):0.670052,((Si_sp|P80815|CWP19_SOLLC:0.30988,(Os_tr|A0A0P0WXB6|A0A0P0WXB6_ORYSJ:5.98808,Si_tr|A0A3Q7GD15|A0A3Q7GD15_SOLLC:5e-09):0.62546):0.251757,((((Os_tr|A0A0P0VQH1|A0A0P0VQH1_ORYSJ:1.38698,((Si_tr|A0A3Q7F2K6|A0A3Q7F2K6_SOLLC:0.233906,(Os_tr|A0A0P0WYV3|A0A0P0WYV3_ORYSJ:0.11088,Zm_tr|C0PGC4|C0PGC4_MAIZE:0.169468):0.267878):0.524298,(((Os_tr|A0A0P0XQ21|A0A0P0XQ21_ORYSJ:0.206431,(Zm_tr|C0PEI3|C0PEI3_MAIZE:0.0527977,(Zm_tr|A0A1D6I6S8|A0A1D6I6S8_MAIZE:0.149095,Zm_tr|A0A1D6I9M3|A0A1D6I9M3_MAIZE:0.0172411):0.0425241):0.0876414):0.373555,((Si_tr|A0A3Q7FMJ7|A0A3Q7FMJ7_SOLLC:0.471268,(((At_sp|Q9ZSB0|SBT39_ARATH:0.0223496,At_sp|Q9ZSB1|SBT3A_ARATH:0.0457853):0.242475,((At_sp|Q9MAP4|SBT32_ARATH:0.0681049,At_tr|Q1PFP8|Q1PFP8_ARATH:0.0504648):0.276127,((At_sp|Q8L7I2|SBT36_ARATH:0.0961071,(At_sp|Q9SZY3|SBT38_ARATH:0.0812613,(At_tr|A0A1P8B3Q4|A0A1P8B3Q4_ARATH:5e-09,(At_sp|Q9SZY2|SBT37_ARATH:5e-09,At_tr|A0A1P8B3T3|A0A1P8B3T3_ARATH:5e-09):5e-09):0.0974708):0.0359175):0.0660699,((At_tr|A0A1P8ASH6|A0A1P8ASH6_ARATH:0.0345701,(At_sp|Q9MAP7|SBT35_ARATH:5e-09,At_tr|A0A1P8ASH5|A0A1P8ASH5_ARATH:5e-09):5e-09):0.10094,(At_sp|Q9MAP5|SBT33_ARATH:0.106663,(At_sp|F4HPF1|SBT34_ARATH:5e-09,At_tr|A0A1P8AMB9|A0A1P8AMB9_ARATH:5e-09):0.092165):0.0275047):0.0537994):0.0956187):0.0301779):0.118263,((At_sp|F4JJH4|SBT31_ARATH:0.6212,(At_sp|Q8GUK4|SBT3D_ARATH:0.0683472,(At_sp|F4JJL8|SBT3F_ARATH:0.0487006,At_sp|Q9SVT4|SBT3E_ARATH:0.0566369):0.0454786):0.318521):0.018353,((At_sp|Q1PDX5|SBT3B_ARATH:0.507004,(At_sp|F4JJH5|SBT3C_ARATH:0.00160632,At_tr|A0A2H1ZEN8|A0A2H1ZEN8_ARATH:5e-09):0.499344):0.106373,(At_sp|Q9C7U8|SBT3H_ARATH:0.356099,At_sp|Q8GWX9|SBT3G_ARATH:0.370562):0.118968):0.0546069):0.0669784):0.121435):0.198818,(Os_tr|Q0ITF8|Q0ITF8_ORYSJ:0.550438,(((Os_tr|Q0JF92|Q0JF92_ORYSJ:0.179652,(Os_tr|A0A0P0W683|A0A0P0W683_ORYSJ:0.179745,Os_tr|Q0JF91|Q0JF91_ORYSJ:0.15978):0.0491617):0.389885,(((Os_tr|Q0JIK4|Q0JIK4_ORYSJ:0.209109,Os_tr|Q0JIK5|Q0JIK5_ORYSJ:0.165038):0.154275,((Os_tr|Q5ZBR8|Q5ZBR8_ORYSJ:0.0873158,Os_tr|Q8RVA0|Q8RVA0_ORYSJ:0.048661):0.0816474,(Os_tr|A0A0P0V984|A0A0P0V984_ORYSJ:0.191418,(Zm_tr|A0A1D6N9J5|A0A1D6N9J5_MAIZE:0.138019,Zm_tr|A0A1D6N9J8|A0A1D6N9J8_MAIZE:0.0656763):0.124827):0.038615):0.129664):0.239953,((Zm_tr|A0A1D6F706|A0A1D6F706_MAIZE:0.0577046,Zm_tr|C0PHQ7|C0PHQ7_MAIZE:0.0906945):0.325516,(((Os_tr|A0A0P0VHD8|A0A0P0VHD8_ORYSJ:0.261564,(Os_tr|A0A0P0VHE8|A0A0P0VHE8_ORYSJ:0.0156034,Os_tr|Q0E256|Q0E256_ORYSJ:0.170543):0.0483504):0.0740312,(Os_tr|Q6EPJ5|Q6EPJ5_ORYSJ:0.115937,Os_tr|Q0E251|Q0E251_ORYSJ:0.181932):0.0659459):0.0192171,Os_tr|A0A0P0VHD1|A0A0P0VHD1_ORYSJ:0.190211):0.0719207):0.205001):0.0425899):0.0921936,(Zm_tr|B4FAJ9|B4FAJ9_MAIZE:0.296227,(Os_tr|B7F194|B7F194_ORYSJ:0.641849,(Os_tr|A0A0P0W6P0|A0A0P0W6P0_ORYSJ:0.167787,((Os_tr|Q7XT44|Q7XT44_ORYSJ:0.0851287,Os_tr|A0A0P0W669|A0A0P0W669_ORYSJ:0.250489):0.0357594,(Os_tr|A0A0P0W6Q2|A0A0P0W6Q2_ORYSJ:0.0664232,(Os_tr|A0A0P0W6V1|A0A0P0W6V1_ORYSJ:0.210412,Os_tr|A0A0P0W6R0|A0A0P0W6R0_ORYSJ:0.0637643):0.0237752):0.0628192):0.134323):0.0907689):0.114941):0.207253):0.106551):0.177952):0.0827494):0.160597,((At_sp|Q9STQ2|SBT3I_ARATH:0.00173141,At_tr|A0A1P8B4U4|A0A1P8B4U4_ARATH:0.0139046):0.595166,(Os_tr|A0A0P0VTL0|A0A0P0VTL0_ORYSJ:0.186937,Zm_tr|A0A1D6JP43|A0A1D6JP43_MAIZE:0.148231):0.299349):0.370374):0.141105):0.00655896):0.0621959,(((Si_tr|A0A3Q7FJS9|A0A3Q7FJS9_SOLLC:0.637476,((At_sp|Q9LLL8|SBT4E_ARATH:5e-09,At_tr|A0A1P8B4Y8|A0A1P8B4Y8_ARATH:0.0350525):0.636404,(Si_tr|A0A3Q7HZF2|A0A3Q7HZF2_SOLLC:0.441368,(At_sp|Q9LZS6|SBT4F_ARATH:0.00187673,At_tr|A0A1P8BDZ1|A0A1P8BDZ1_ARATH:0.00189975):0.417902):0.190091):0.179967):0.0772142,((At_sp|F4IG09|SBT41_ARATH:1.27252,(At_sp|Q9FIF8|SBT43_ARATH:0.488021,((At_sp|O23357|SBT42_ARATH:5e-09,At_tr|A0A1P8B448|A0A1P8B448_ARATH:5e-09):0.600312,((At_sp|F4JA91|SBT45_ARATH:0.0567525,At_sp|Q9STF7|SBT46_ARATH:0.0840895):0.170421,(At_sp|Q9FGU3|SBT44_ARATH:0.243199,((At_tr|A0A1P8B9X7|A0A1P8B9X7_ARATH:5e-09,(At_sp|Q9FIG1|SBT4B_ARATH:5e-09,At_tr|F4KHS9|F4KHS9_ARATH:5e-09):5e-09):0.249141,((At_sp|Q9FIG2|SBT4D_ARATH:0.0936112,(At_tr|F4KHS2|F4KHS2_ARATH:5e-09,(At_sp|Q8L7D2|SBT4C_ARATH:5e-09,At_tr|F4KHS1|F4KHS1_ARATH:5e-09):5e-09):0.126932):0.0951968,((At_tr|Q9FIG3|Q9FIG3_ARATH:0.168336,((At_sp|Q9FIM5|SBT49_ARATH:5e-09,(At_tr|A0A1P8BDQ6|A0A1P8BDQ6_ARATH:0.00360062,At_tr|A0A1P8BDT9|A0A1P8BDT9_ARATH:0.0126486):0.0250376):0.126717,At_sp|Q9FIM8|SBT4A_ARATH:0.190827):0.0179254):0.0298084,(At_sp|Q9FIM6|SBT48_ARATH:0.120292,At_sp|F4KGD4|SBT47_ARATH:0.165826):0.0345855):0.0774906):0.0420932):0.115935):0.0465372):0.194231):0.0957521):0.133451):0.0942338,(Zm_tr|A0A1D6HUV8|A0A1D6HUV8_MAIZE:0.311228,(Zm_tr|A0A1D6HUV9|A0A1D6HUV9_MAIZE:0.177238,(Zm_tr|A0A1D6HUV7|A0A1D6HUV7_MAIZE:0.0161883,Zm_tr|A0A1D6I7N0|A0A1D6I7N0_MAIZE:0.30347):0.147155):0.200775):0.362192):0.0960166):0.250344,((Os_tr|Q9LJ20|Q9LJ20_ORYSJ:0.146087,Zm_tr|A0A1D6MQX9|A0A1D6MQX9_MAIZE:0.0839298):0.563916,((Os_tr|C7J6W5|C7J6W5_ORYSJ:0.122939,Zm_tr|A0A1D6HXI1|A0A1D6HXI1_MAIZE:0.176326):0.280717,(At_sp|F4HSQ2|SBT51_ARATH:0.618411,((At_sp|Q9LNU1|CRSP_ARATH:0.00108847,At_tr|A0A1P8AUU9|A0A1P8AUU9_ARATH:0.048241):0.367667,(Si_tr|A0A3Q7H3L3|A0A3Q7H3L3_SOLLC:0.238037,Si_tr|A0A3Q7ERD5|A0A3Q7ERD5_SOLLC:0.469272):0.168506):0.0533825):0.149522):0.152732):0.245571):0.0851232):0.0845565,((Os_tr|A0A0P0W6B4|A0A0P0W6B4_ORYSJ:1.96891,(((Os_tr|A0A0P0XEJ6|A0A0P0XEJ6_ORYSJ:0.146945,Zm_tr|A0A1D6LCF9|A0A1D6LCF9_MAIZE:0.171168):0.539259,((Os_tr|B9G469|B9G469_ORYSJ:0.0952269,Zm_tr|A0A1D6I6P5|A0A1D6I6P5_MAIZE:0.133858):0.259836,((At_sp|F4JXC5|SBT54_ARATH:0.413207,(At_sp|Q9ZSP5|AIR3_ARATH:0.372531,(Si_tr|A0A3Q7HDL2|A0A3Q7HDL2_SOLLC:0.121181,Si_tr|A0A3Q7JSW9|A0A3Q7JSW9_SOLLC:0.301083):0.152285):0.0884276):0.0867074,((Zm_tr|K7VJE6|K7VJE6_MAIZE:0.258739,Os_tr|Q0DB15|Q0DB15_ORYSJ:0.309268):0.167613,(Os_tr|Q6H733|Q6H733_ORYSJ:0.204786,(Zm_tr|A0A1D6QR85|A0A1D6QR85_MAIZE:0.752791,Zm_tr|A0A1D6H400|A0A1D6H400_MAIZE:5e-09):0.195168):0.126127):0.13212):0.0430012):0.0882921):0.0892507,((Os_tr|A0A0P0V749|A0A0P0V749_ORYSJ:0.126151,Os_tr|A0A0P0VXK0|A0A0P0VXK0_ORYSJ:2.12134):0.158439,Zm_tr|A0A1D6NEK4|A0A1D6NEK4_MAIZE:0.233975):0.400057):0.100849):0.120372,((Os_tr|Q0JJP0|Q0JJP0_ORYSJ:0.0901925,Zm_tr|A0A1D6NDF4|A0A1D6NDF4_MAIZE:0.13058):0.315425,(Si_tr|A0A3Q7F4F5|A0A3Q7F4F5_SOLLC:0.328944,((Si_tr|A0A3Q7JH74|A0A3Q7JH74_SOLLC:0.202878,Si_tr|A0A3Q7F2H5|A0A3Q7F2H5_SOLLC:0.0757041):0.38078,(At_sp|Q9FK76|SBT56_ARATH:0.118086,At_sp|F4KEL0|SBT55_ARATH:0.289593):0.255795):0.0937289):0.112606):0.311467):0.0438198):0.0812187,((Zm_tr|A0A1D6E6T4|A0A1D6E6T4_MAIZE:0.935691,((((Os_tr|Q10RX3|Q10RX3_ORYSJ:0.0954611,Zm_tr|A0A1D6JNE6|A0A1D6JNE6_MAIZE:0.136694):0.251213,(At_sp|O64495|SBT12_ARATH:0.25684,(Si_tr|A0A3Q7IZL0|A0A3Q7IZL0_SOLLC:0.131877,Si_tr|A0A3Q7HYL4|A0A3Q7HYL4_SOLLC:0.135809):0.136093):0.150527):0.411168,((((((Os_tr|Q8RVC2|Q8RVC2_ORYSJ:0.0695868,Zm_tr|B6SWF4|B6SWF4_MAIZE:0.11347):0.0834635,(Os_tr|Q8H047|Q8H047_ORYSJ:0.0900359,(Zm_tr|A0A1D6PL21|A0A1D6PL21_MAIZE:0.0748935,Zm_tr|A0A1D6JLG5|A0A1D6JLG5_MAIZE:0.0316886):0.0761186):0.112551):0.407302,((Os_tr|Q0DIR5|Q0DIR5_ORYSJ:0.266794,Zm_tr|B4FAT5|B4FAT5_MAIZE:0.188053):0.223667,(Os_tr|Q0D3H9|Q0D3H9_ORYSJ:0.35506,(Os_tr|A0A0P0VYZ5|A0A0P0VYZ5_ORYSJ:0.380637,Zm_tr|A0A1D6INV6|A0A1D6INV6_MAIZE:0.296152):0.0889095):0.161801):0.321676):0.0423059,(Os_tr|B9GCW9|B9GCW9_ORYSJ:0.297926,Zm_tr|C0HGM2|C0HGM2_MAIZE:0.271279):0.419822):0.060419,(((Os_tr|Q7XSC3|Q7XSC3_ORYSJ:0.306898,Zm_tr|K7TN98|K7TN98_MAIZE:0.28327):0.470798,((Os_tr|Q7XPR9|Q7XPR9_ORYSJ:0.214198,Zm_tr|K7TRW1|K7TRW1_MAIZE:0.254726):0.199166,(Os_tr|Q6ESH8|Q6ESH8_ORYSJ:0.242632,Zm_tr|A0A1D6HFE8|A0A1D6HFE8_MAIZE:0.258392):0.0902433):0.368948):0.20967,(((Zm_tr|A0A1D6E3K3|A0A1D6E3K3_MAIZE:0.143257,Zm_tr|A0A1D6I1L9|A0A1D6I1L9_MAIZE:0.21567):0.0967521,(Os_tr|A0A0P0XXE6|A0A0P0XXE6_ORYSJ:0.106184,Os_tr|Q7XPR8|Q7XPR8_ORYSJ:0.069571):0.133866):0.0742615,(Zm_tr|A0A1D6ECS6|A0A1D6ECS6_MAIZE:0.212394,Zm_tr|A0A1D6E3K4|A0A1D6E3K4_MAIZE:0.155506):0.119838):0.29989):0.0999329):0.053306,((Si_tr|A0A3Q7HTN5|A0A3Q7HTN5_SOLLC:0.116866,Si_tr|A0A3Q7HVK1|A0A3Q7HVK1_SOLLC:0.19641):0.282833,((Si_tr|A0A3Q7FPL6|A0A3Q7FPL6_SOLLC:0.366146,((((Si_tr|A0A3Q7IMY0|A0A3Q7IMY0_SOLLC:0.152684,Si_tr|A0A3Q7IMX6|A0A3Q7IMX6_SOLLC:0.171955):0.148664,(Si_tr|A0A3Q7FPK9|A0A3Q7FPK9_SOLLC:0.182746,Si_tr|A0A3Q7F4S7|A0A3Q7F4S7_SOLLC:0.196909):0.0427176):0.198063,Si_tr|A0A3Q7F3D9|A0A3Q7F3D9_SOLLC:0.253835):0.0832125,((Si_tr|A0A3Q7HVI0|A0A3Q7HVI0_SOLLC:0.0617823,(Si_tr|A0A3Q7HTM2|A0A3Q7HTM2_SOLLC:0.0843394,Si_tr|A0A3Q7HVI4|A0A3Q7HVI4_SOLLC:0.0609184):0.0329911):0.148133,(Si_tr|A0A3Q7HHX1|A0A3Q7HHX1_SOLLC:0.204689,(Si_tr|A0A3Q7HI18|A0A3Q7HI18_SOLLC:0.121985,Si_tr|A0A3Q7HKM1|A0A3Q7HKM1_SOLLC:0.12421):0.0636677):0.0380551):0.223914):0.015768):0.021057,((Si_tr|A0A3Q7F3D6|A0A3Q7F3D6_SOLLC:0.256448,Si_tr|A0A3Q7H813|A0A3Q7H813_SOLLC:0.582246):0.245194,((Si_tr|A0A3Q7HTN1|A0A3Q7HTN1_SOLLC:0.0838157,Si_tr|K4CNZ6|K4CNZ6_SOLLC:0.173553):0.0440359,(Si_tr|K4CNZ7|K4CNZ7_SOLLC:0.11566,Si_tr|A0A3Q7HVJ4|A0A3Q7HVJ4_SOLLC:0.237615):0.02966):0.208701):0.0375301):0.0583451):0.213752):0.275327):0.0316933,Zm_tr|A0A1D6MDQ7|A0A1D6MDQ7_MAIZE:0.597081):0.0750813):0.0461527,(((((Os_tr|Q10P89|Q10P89_ORYSJ:0.074154,Zm_tr|A0A1D6JVP9|A0A1D6JVP9_MAIZE:0.0962093):0.279995,(At_sp|O49607|SBT16_ARATH:0.181163,Si_tr|A0A3Q7EU46|A0A3Q7EU46_SOLLC:0.167547):0.108742):0.193509,(Si_tr|A0A3Q7FGH5|A0A3Q7FGH5_SOLLC:0.571302,((Os_tr|A0A0P0XGM3|A0A0P0XGM3_ORYSJ:0.117974,Zm_tr|K7UTX5|K7UTX5_MAIZE:0.0838403):0.27316,(At_sp|Q9LUM3|SBT15_ARATH:0.169807,Si_tr|A0A3Q7FWI6|A0A3Q7FWI6_SOLLC:0.191101):0.0921138):0.182519):0.0932157):0.136759,(((At_sp|Q9LVJ1|SBT14_ARATH:0.325311,Si_tr|A0A3Q7GY58|A0A3Q7GY58_SOLLC:0.231489):0.0931102,((((Si_tr|A0A3Q7G5Y8|A0A3Q7G5Y8_SOLLC:1.02536,(Os_tr|Q6K7F9|Q6K7F9_ORYSJ:0.208646,Os_tr|Q6K7F4|Q6K7F4_ORYSJ:0.19198):0.255371):5e-09,(Os_tr|Q6K7G6|Q6K7G6_ORYSJ:0.186273,Os_tr|A0A0P0VQA5|A0A0P0VQA5_ORYSJ:0.310179):0.208286):0.0833699,(Zm_tr|K7U9N2|K7U9N2_MAIZE:0.148595,Zm_tr|A0A1D6HM48|A0A1D6HM48_MAIZE:0.225221):0.140327):0.197081,(Os_tr|Q6K7G5|Q6K7G5_ORYSJ:0.0972729,Zm_tr|A0A1D6HM49|A0A1D6HM49_MAIZE:0.135683):0.140905):0.159826):0.233888,(((At_sp|Q9ZUF6|SBT18_ARATH:0.226001,(Si_tr|A0A3Q7HRU5|A0A3Q7HRU5_SOLLC:0.349262,Si_tr|A0A3Q7H8H1|A0A3Q7H8H1_SOLLC:0.166869):0.0583964):0.173011,((Os_tr|Q69P78|Q69P78_ORYSJ:0.0729534,Zm_tr|B4FAI3|B4FAI3_MAIZE:0.106051):0.33512,(Os_tr|A0A0P0XUA3|A0A0P0XUA3_ORYSJ:0.0970392,Zm_tr|A0A1D6KW13|A0A1D6KW13_MAIZE:0.129766):0.211421):0.137911):0.177595,(((Os_tr|A0A0P0WDQ9|A0A0P0WDQ9_ORYSJ:0.169271,Zm_tr|C0P5D8|C0P5D8_MAIZE:0.0821208):0.170142,(At_sp|Q9FLI4|SBT13_ARATH:0.231046,Si_tr|P93205|P93205_SOLLC:0.227979):0.151756):0.330052,(((Os_tr|Q94H95|Q94H95_ORYSJ:0.0806944,Zm_tr|A0A1D6L5J9|A0A1D6L5J9_MAIZE:0.0739161):0.181787,(Os_tr|Q75I27|Q75I27_ORYSJ:0.0782179,Zm_tr|A0A1D6KWW2|A0A1D6KWW2_MAIZE:0.0956513):0.147993):0.108223,(Si_tr|A0A3Q7H1P2|A0A3Q7H1P2_SOLLC:0.327901,(At_sp|O65351|SBT17_ARATH:0.19875,(Si_tr|A0A3Q7FB69|A0A3Q7FB69_SOLLC:0.16396,Si_tr|A0A3Q7FGM4|A0A3Q7FGM4_SOLLC:0.127319):0.074917):0.0804888):0.0622086):0.162061):0.0622231):0.062397):0.0569829):0.105433,((Os_tr|Q6ZL89|Q6ZL89_ORYSJ:0.265282,(Zm_tr|C0HF77|C0HF77_MAIZE:0.0883331,Zm_tr|C0HFN9|C0HFN9_MAIZE:0.0771535):0.274885):0.698732,(((Os_tr|Q0JD53|Q0JD53_ORYSJ:0.168666,Zm_tr|A0A1D6EAQ6|A0A1D6EAQ6_MAIZE:0.183704):0.566099,(((Os_tr|Q8S1N3|Q8S1N3_ORYSJ:0.283844,(Os_tr|Q6I5K9|Q6I5K9_ORYSJ:0.13634,Zm_tr|A0A1D6FPN2|A0A1D6FPN2_MAIZE:0.181068):0.065936):0.255904,(At_sp|Q9FHA4|SBT19_ARATH:0.806955,(Si_tr|A0A3Q7GA54|A0A3Q7GA54_SOLLC:0.155908,(Si_tr|A0A3Q7JBV7|A0A3Q7JBV7_SOLLC:0.162533,Si_tr|A0A3Q7JCS2|A0A3Q7JCS2_SOLLC:0.0802834):0.0949745):0.221513):0.154566):0.0839584,((Os_tr|A0A0P0VAS5|A0A0P0VAS5_ORYSJ:0.206473,Zm_tr|K7VAR5|K7VAR5_MAIZE:0.230801):0.316621,(Si_tr|A0A3Q7G6K3|A0A3Q7G6K3_SOLLC:0.344584,((Si_tr|A0A3Q7EIV2|A0A3Q7EIV2_SOLLC:0.175884,Si_tr|A0A3Q7F307|A0A3Q7F307_SOLLC:0.0453024):0.57658,((Si_tr|A0A3Q7F302|A0A3Q7F302_SOLLC:0.145559,(Si_tr|A0A3Q7IM32|A0A3Q7IM32_SOLLC:0.118791,(Si_tr|A0A3Q7IMQ2|A0A3Q7IMQ2_SOLLC:0.208044,Si_tr|A0A3Q7JGF7|A0A3Q7JGF7_SOLLC:0.00561839):0.132923):0.152389):0.069226,(((((Os_tr|A0A0P0V7R1|A0A0P0V7R1_ORYSJ:1.54271,Si_tr|A0A3Q7F328|A0A3Q7F328_SOLLC:4.3e-08):0.0606424,(Si_tr|A0A3Q7EIV5|A0A3Q7EIV5_SOLLC:0.0342549,Si_tr|O82006|O82006_SOLLC:0.0298434):0.108903):0.0273602,(Si_tr|Q9ZS44|Q9ZS44_SOLLC:0.0639951,Si_tr|A0A3Q7EJ69|A0A3Q7EJ69_SOLLC:0.0658596):0.0155231):0.016159,Si_tr|A0A3Q7F322|A0A3Q7F322_SOLLC:0.0904761):0.0684392,(Si_sp|O82777|SBT3_SOLLC:0.0239044,Si_tr|K4AYH3|K4AYH3_SOLLC:0.293759):0.0360273):0.117765):0.104016):0.210488):0.127292):0.0954303):0.241227):0.191043,(At_sp|Q84WS0|SBT11_ARATH:0.520529,Si_tr|A0A3Q7EKM2|A0A3Q7EKM2_SOLLC:0.386539):0.311761):0.06905):0.0369007):0.0650296):0.133483):0.172483):0.0846652):0.335914):0.0753276);

**Comment by xgrau** [comment]
This was an odd bug indeed, it took me a while to figure it out... but I think it's fixed now. Please try redownloading possvm and see if it works. 

Basically, last April I made some changes to accommodate the need to set edge weights in `networkx` ([this commit](https://github.com/xgrau/possvm-orthology/commit/0a2af1868bcae93416a049e79fe5066fdec85d02)) and this had the unadvertent effect of changing how `markov_cluster` dealt with clusters, resulting in certain genes being assigned to more than one cluster! Which then created all these inconsistent entries in the homology files, as pairwise gene relationships were being recorded multiple times.

Also, please confirm that you downloaded possvm after 8th of April 2024, which is when this odd behaviour must have started.

Unrelated issue: I'm not sure if you're denoting the species separator correclty (is it the underscore `_` or the pipe `|` character? You can change it with `-split "|"` if necessary)

Thanks for reaching out!

**Comment by biowander** [comment]
Thank you for your response and your suggestions. The aforementioned issue has been resolved! However, I still have a few questions. Could you please explain in detail the meaning of terms such as "in” and “_int” in "inparalog_int" and other similar terms like “out” and “_ext”? From my understanding, there are some gene pairs within the same species that were formed by duplication events that occurred before the speciation event and should be defined as outparalogs. However, in the results from possvm, these are classified as inparalogs. I am not sure if my understanding is correct. Thank you for your response!

**Comment by biowander** [comment]
Thank you again for your patient response.
